In [1]:
import pandas as pd
from numpy.random import default_rng
from time import time
from mtjjv_sketch import *
from stainer_new import *
from history import *

In [2]:
df = pd.DataFrame([(0, 'Cat'), (1, 'Dog'), (2, 'Rabbit'), (3, 'Cat'), (4, 'Cat'), (5, 'Dog')],
                  columns=('id', 'class'))

# Shuffle

In [3]:
stain = ShuffleStainer()

In [4]:
res = DirtyDF(df, seed = 214).add_stainers(stain).add_stainers(stain).run_all_stainers()
res.get_df()

id   class
0   2  Rabbit
1   5     Dog
2   4     Cat
3   1     Dog
4   0     Cat
5   3     Cat

In [5]:
# Original DF is unmodified
df

id   class
0   0     Cat
1   1     Dog
2   2  Rabbit
3   3     Cat
4   4     Cat
5   5     Dog

In [6]:
res.get_map_from_history(0)

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [7]:
res.get_previous_map()

array([[0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0.]])

In [8]:
res.get_mapping(axis = 0)

array([[0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.]])

In [9]:
res.get_mapping(axis = 1)

array([[1., 0.],
       [0., 1.]])

In [10]:
new_ddf = DirtyDF(df, seed = 214).add_stainers(stain).run_stainer()
new_ddf.add_stainers(stain).run_stainer().get_df()

id   class
0   2  Rabbit
1   5     Dog
2   4     Cat
3   1     Dog
4   0     Cat
5   3     Cat

In [11]:
res.print_history()

1. Shuffle 
 Order of rows randomized 
 Time taken: 0.0010190010070800781 

2. Shuffle 
 Order of rows randomized 
 Time taken: 0.0009779930114746094 

